from pathlib import Path
PROJECT_ROOT=Path(__file__).resolve().parents[1]
DATA_DIR=PROJECT_ROOT/'data'; RAW_DIR=DATA_DIR/'raw'; CLEAN_DIR=DATA_DIR/'clean'; FEATURE_DIR=DATA_DIR/'features'
OUTPUT_DIR=PROJECT_ROOT/'outputs'; TRADE_DIR=OUTPUT_DIR/'trades'; REPORT_DIR=OUTPUT_DIR/'reports'; LOG_DIR=OUTPUT_DIR/'logs'
for d in [RAW_DIR,CLEAN_DIR,FEATURE_DIR,TRADE_DIR,REPORT_DIR,LOG_DIR]: d.mkdir(parents=True,exist_ok=True)
SYMBOLS=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT']
INTERVAL='5m'; START_DATE='2021-01-01'; END_DATE='2026-01-01'
BINANCE_BASE_URL='https://api.binance.com'; KLINES_ENDPOINT='/api/v3/klines'
INITIAL_CASH=100_000.0; MAX_POSITION_PCT=0.25; MAX_GROSS_EXPOSURE=1.0; TAKER_FEE_BPS=7.5; SLIPPAGE_BPS=2.5
